var a=10;
var b=20;
var c=a+b;
console.log("the addition is:",c);
var s=1;
var t=2;
var g=s-t;
console.log("the substraction is:",g);
let j=10;
let i=2;
let k=i*j;
console.log("the multiplication is:",k);
let d=50;
let e=10;
let f=d/e;
console.log("the division of :",f);
const z=20;
const x=10;
const y=z%x;
console.log("the modular division is:",y);
